### ISSUE TITLE
[bug?] dotenv command $VARIABLE

### ISSUE THREAD

**Issue by jjangga0214** [entropitor/dotenv-cli#23]
Hi, thank you for this convenient cli :)

I found a strange behavior. dotenv does not work with direct use of an environment variable. 

Let's say my **.env** file is like the below.

```bash
# content of .env
MESSAGE=helloworld
```

I expect the command below would print "helloworld" on the console.

```bash
$ dotenv echo $MESSAGE
```

However, it doesn't. If an environment variable is directly used on the command after dotenv, then the value is not properly populated.

So, assume I made a file **.greeting.sh** like this.

```bash
# content of .greeting.sh
echo $MESSAGE
```

And I changed the command like the below.

```bash
$ dotenv ./greeting.sh
```

And now it works!

This might be quite unexpected to users, isn't it?
I think it'd be better to allow direct use of environment variables after dotenv.
How do you feel?

Thanks.

**Comment by entropitor** [comment]
Hey! Thanks for the bug report. The problem is with the way the shell works. If you run
```bash
$ dotenv echo $MESSAGE
```
your shell will first interpolate the value `$MESSAGE` and then run the command with the value interpolated
```
$ dotenv echo ""
```

so `dotenv-cli` will get the arguments `echo ""` so it's impossible to know that `$MESSAGE` was passed. 

What you could do: launch a bash shell with the command "echo $MESSAGE". For this to work, you need to escape the $ or use single quotes
```bash
dotenv -- bash -c "echo \$MESSAGE"
dotenv -- bash -c 'echo $MESSAGE'
```

I hope this helps
