### ISSUE TITLE
Override system variables

### ISSUE THREAD

**Issue by mobula9** [entropitor/dotenv-cli#62]
Hello,

the override system is now available is dotenv (https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1410-2022-01-17)

It would be nice to get it in dotenv-cli

Have a nice day!

**Comment by entropitor** [comment]
What kind of flags would you like `dotenv-cli` to have? How should it behave?

**Comment by entropitor** [comment]
@raxityo that's already possible by using the right order of -e flags, have you tried switching the order? See also https://github.com/entropitor/dotenv-cli#cascading-env-variables for an alternative to this

This issue is about having a API_TOKEN as a env variable in your shell and ignoring that and only listening to the ones in the .env file (by default the ones in your shell take precedence)

**Comment by raxityo** [comment]
Aha thanks, the order of `-e` is what I was misinterpreting in my example case.

However, my example illustrates a basic scenario where env variables are exclusively provided through `dotenv`.
In a more real-world scenario, some environment variables (such as: `LOG_LEVEL`, `NODE_ENV`, etc.) are set at the time of creating the docker image and we'd like to change their values (eg: `LOG_LEVEL=info` instead of `warn`, `NODE_ENV` to `test`  instead of `production`) when running a particular command on that container.

**Comment by aterreno** [comment]
I am having the same exact use case as @raxityo where I'd like to have a base config, good for development, which gets overwritten with secret values at CI/CD build/compilation. 

thanks

**Comment by entropitor** [comment]
@aterreno Or you can use the `-c development` flag and have a `.env` useful for all environments and `.env.development` for local development and then in CI you don't use `-c development` and then you can just set the env variables.

Also, I think this is the reverse use-case. This issue is about when you WANT to override the env variables already set. In CI, you can just set the env variables already and then doing `dotenv -e .env` will not override the ones from the CI.

**Comment by rhyek** [comment]
I have a monorepo with a global .env file that provides values for all applications. These are loaded by another utility (`direnv`) and are useful not just for node programs, but several project scripts I run on the command line. So these are available on the shell.

I have per-app scripts for unit/e2e testing where I want to override certain values when invoking them. For example `NODE_ENV`, or database connection strings. The use-case has already been discussed enough on the `dotenv` project and since they now support the override feature, I believe this project should too.

This fork is an example of how to implement a flag for it: https://github.com/t1m0thyj/dotenv-override-cli

**Comment by entropitor** [comment]
I welcome a PR that actually works without reversing the order of the paths in which we load things. Otherwise, I suggest a fork is used indeed 👍
