### ISSUE TITLE
Conflicting options: 'override' and 'cascade'

### ISSUE THREAD

**Issue by llovett2** [entropitor/dotenv-cli#89]
The `override` option introduced in https://github.com/entropitor/dotenv-cli/pull/87 by @jfairley conflicts with the `cascade` option when both are used together.

#### .env
```
MY_NAME=Bob
```

#### .env.local
```
MY_NAME=Joe
```

#### Command
```
> dotenv -c -- bash -c 'echo $MY_NAME'
Joe
> dotenv -co -- bash -c 'echo $MY_NAME'
Bob
```

I would expect `Joe` from `.env.local` to override `Bob` from `.env` based on how `cascade` works, but when the  `override` option is present `Bob` prevails because `.env` is processed last (see [here](https://github.com/entropitor/dotenv-cli/blob/a4962032bc52eb61d5fa35db29d1e731c14a00b2/cli.js#L46) and [here](https://github.com/entropitor/dotenv-cli/blob/a4962032bc52eb61d5fa35db29d1e731c14a00b2/cli.js#L75)).

**Comment by jfairley** [comment]
That's interesting. You raise a valid point, but I'm not sure how to easily make both work together. The problem is `dotenv` doesn't support "cascade" natively. There's probably no way to avoid edge cases without `dotenv` supporting cascade natively.

**Comment by llovett2** [comment]
What if we reversed the `paths` array if `override` is set before iterating through it? I'm trying to think if that will cause any negative side effects.

**Comment by entropitor** [comment]
Yeah, there was an earlier discussion: https://github.com/entropitor/dotenv-cli/pull/63#discussion_r787101557

I think it's just incompatible. Feel free to make a PR to update the README to document this but this is not really solvable. 

I think the best solution is just erroring out if using `override` together with multiple files, ...

**Comment by jfairley** [comment]
Ooh man, this one bit me in the butt the other day.

Like @llovett2 found, when you run override with cascade, the order of files is effectively inverted such that values in `.env` will override `.env.test`.

We need to do something about this, because of the potential impact. In my case, a dev on my team ran unit tests that blew away our QA database.

I'm available to submit a new pull-request, but @entropitor, I'm looking to discover what you're likely to accept, considering this issue was closed before.

1. Invert the files array when `argv.c && argv.o`.
   * I actually believe this is a pretty simple and readable change. I have it ready to go locally.
2. Prevent "cascade with override".
   * Literally throw a runtime error if `argv.c && argv.o` saying it's not supported.

**Comment by entropitor** [comment]
I think it's best to throw. I knew this was a problem when merging that's why I pushed back so hard on cascade. The other solution has a problem with expanding variables so I don't think that's valid either. I guess throwing is the most elegant solution! Happy to merge such a pr
